const mongoose = require('mongoose');

const PlayerSchema = new mongoose.Schema({
  nccRef: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  beltRank: { type: String, required: true },
  birthdate: { type: Date },
  gender: { type: String },
  team: { type: String, required: true },
  photoUrl: { type: String },
  address: { type: String },
  contactNumber: { type: String },
  lastPromotionExam: { type: Date },
  nextBelt: { type: String },
  stats: {
    competitions: [String],
    medals: Number,
    points: Number
  },
  achievements: [String],
  requiredForms: { type: String },
  isAutoGenerated: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Player', PlayerSchema); 