const mongoose = require('mongoose');

const PlayerSchema = new mongoose.Schema({
  nccRef: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  beltRank: { type: String, required: true },
  birthdate: { type: Date },
  gender: { type: String }, // Keep for backward compatibility but will be replaced by team in UI
  team: { type: String, required: true }, // Team assignment (EARIST, ERVHS, ARISE, TONDO, RECTO)
  photoUrl: { type: String },
  address: { type: String },
  contactNumber: { type: String },
  lastPromotionExam: { type: Date },
  nextBelt: { type: String },
  stats: {
    competitions: [String],
    medals: Number,
    points: Number
  },
  achievements: [String],
  requiredForms: { type: String }, // Self-defense forms required for next promotion
  poomsaeForms: { type: String }, // Poomsae forms required for next promotion
  isAutoGenerated: { type: Boolean, default: false }, // Flag for auto-generated NCC Ref
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Player', PlayerSchema);